mawa-za/mawa-flutter-package

lib/services/invoice.dart, lib/services/keys.dart
-Created method to get all invoices
-Added required keys
=> -Created method to get a specific invoice

lib/services/claims.dart, lib/services/keys.dart
-Created get method for a specific claim
-Created post method for creating claim
-Added required keys
=> -Created get method for all claims

lib/services/products.dart, lib/services/purchase_order.dart
modified createPurchaseOrder method on the purchaseOrder class
=> modified productsList method on the products class

lib/services/keys.dart, lib/services/purchase_order.dart
added method to get all purchase orders
=> Get all purchase orders

lib/services/customers.dart, lib/services/keys.dart, lib/services/partners.dart
2. added keys for partner and customer.
3. Added create partner, add contact, add identity, get specific partner, assign partner role endpoint in partners.dart.
=> 1. Modified get all customer endpoint

lib/mawa_package.dart, lib/services/keys.dart, lib/services/organisation.dart, lib/services/prospect.dart, lib/services/supplier.dart
modified mawa_package and relevant keys
=> added prospect,supplier and organization services

lib/services/keys.dart, lib/services/payment_requests.dart
2.Created the file payment_requests.dart,
3.Added payment Request Methods,
=> 1.Added payment request keys,

lib/services/keys.dart, lib/services/partners.dart
2.Modified partner add contact method.
=> 1.Modified field keys,

lib/services/customers.dart, lib/services/keys.dart, lib/services/partners.dart
1.delete partner details,
2.get specif details,
3.add partner Detals.
4.added more partner keys
=> Added More Partner Methods:

lib/services/employees.dart, lib/services/keys.dart, lib/services/partners.dart
2.Updated getSpecif partner details and keys.
=> 1.Updated get all employee method.

lib/services/claims.dart, lib/services/keys.dart
=> modified JsonPayloads keys

pubspec.lock, pubspec.yaml
upgraded dart sdk version and flutter version on the pubspec.yaml file due to the error found on the build
=> sdk upgrade

lib/services/keys.dart, lib/services/partners.dart
added archive and unarchive partner methods.
=> Modified keys,

lib/mawa_package.dart, lib/services.dart, lib/services/field.dart
changed naming from fields to field and updated methods as well as added indentations
=> changed name and updated methods

lib/services/membership.dart
updated membership  methods and added indentations
=> membership  methods updated

lib/services/employment.dart, lib/services/keys.dart
=> 1.added get all employee employment history method,

lib/services/strings.dart
modify get name function on strings class to cater for names not returned properly
=> person name modify

lib/services/products.dart
modified mapping products method to  use recent keys
=> product map

lib/services/membership.dart
modified the receiving of payload attributes and handling of nulls
=> memberships modified payloads

lib/services/keys.dart
=> keys update

lib/services/keys.dart, lib/services/partners.dart
=> 1.Added the function to validate SAID

lib/services/organisation.dart, lib/services/prospect.dart
updated the keys
organisation.dart modified
=> added a function to edit the organisation

lib/services/idnumber_validation.dart, lib/services/partners.dart
2.Added moved a method validateID to it owm file.
=> 1.Added file idnumber_validation.

lib/services/keys.dart, lib/services/organisation.dart
added functionality of addresses to edit the 
updated the keys
organisation.dart modified
=> Organisation modify

lib/services/claims.dart, lib/services/keys.dart
updated the keys
claim.dart modified
=> added functionality to add banking details to a claim

lib/services/keys.dart
=> new variables to keys.dart

lib/services/user.dart
- added a filed to hold and pass the partner ID in the create method
- corrected the resource path for role delete
=> Testing (Users): Named parameter does not exist error#365

lib/services/products.dart
- removed unnecessary and unused variables
- reconfigured the methods
- added indentations
- renamed some methods
=> Testing (Membership): Products get error#266

lib/services/keys.dart
=> Testing (build): build automated build failed#270

lib/services/idnumber_validation.dart, lib/services/keys.dart
corrected identity and identities wording on resources
=> Testing (Memberships): Can't Create Membership #292

lib/services/keys.dart, lib/services/vouchers.dart
1. Added voucher CRUD methods.
2. Modified voucher keys.
=> Testing (Customer): Voucher Panel Missing #280(package)

lib/screens/alerts.dart, lib/screens/overlay_widgets.dart
- changed toastmessage background color for for web to white
- added indentations
=> Testing (alerts): alert messages are not readable#320

lib/services/vouchers.dart
1. Modified the get all voucher method;
=> Testing (Customer): Voucher Panel Missing issue:'#280'(package)

example/macos/Flutter/GeneratedPluginRegistrant.swift, example/pubspec.lock, example/windows/flutter/generated_plugin_registrant.cc, example/windows/flutter/generated_plugins.cmake, lib/screens/alerts.dart, lib/services/constants.dart, lib/services/strings.dart, lib/services/tools.dart, lib/services/transaction_notes.dart, pubspec.lock, pubspec.yaml
upgraded packages awesome_dialog, flutter_animate, and  dropdown_search to berid of the build error
=> Github merge to development error#396

example/lib/home.dart, example/pubspec.lock, example/pubspec.yaml, pubspec.lock, pubspec.yaml
updated the dart version to match the mawa project
=> Github merge to development error #430 #432

lib/screens/attach_base64_file.dart, lib/services/attachment.dart, lib/services/keys.dart
=> Attachments - All Work centres #390

lib/mawa_package.dart, lib/services/keys.dart, lib/services/service_request.dart
- Added create, get all, get specific, delete service request methods
=> - Added the service request file

lib/services/membership.dart
added tombstone recipient related methods with their respective endpoint calls
=> Development(membership): show tombstone recipient on membership view#482

lib/services/membership.dart
=> Github Merge pull request #503 fail#402

lib/services/partners.dart
- added valid from, and valid to as part as add identity payload .
=> Testing (Customer): Add Passport Validity #532

lib/screens/change_password.dart, lib/screens/otp.dart
=> Testing (System Configuration): Change Password not functioning #525

lib/services/receipts.dart
=> Testing(Cashup): Filter receipts for cashing up #519

lib/services/keys.dart, lib/services/membership.dart
=> Testing (Membership): Membership Create - Transfers #548

lib/services/keys.dart
=> added CITY to FieldOptionTypes

lib/services/partners.dart
=> Testing ( Cash up) View and Create Amendments #642

lib/services/claims.dart, lib/services/keys.dart
-added the submit claim method
-added the dispute claim method
claims.dart modified
keys.dart modified
=> Testing (Claims) Add a dispute button #558

lib/services/keys.dart, lib/services/products.dart
- added new keys
- added validity dates to product attribute create and pricing create methods
=> Testing (System Configuration :Product): View updates#660

lib/services/keys.dart
- added new field option types to keys
- created a membership type class
=> Group Memberships Work center #664

lib/mawa_package.dart, lib/services/keys.dart, lib/services/premium.dart
- created new class Premium, its methods, resource key, payload keys and query parameter keys
=> Developmemnt(Premium): Implementation#672

example/lib/home.dart, lib/screens/attach_base64_file.dart, lib/services/attachment.dart, lib/services/keys.dart
=> Memberships Attachments Panel Needed #555

lib/screens/attach_base64_file.dart, lib/services/keys.dart
=> Testing(attachment) modify add attachment popup#705

lib/services/keys.dart, lib/services/membership.dart
- changed tombstone create 
- added payload key
=> Testing (Membership) : Dependent Create Screen Adjustments #616

lib/services/claims.dart
modified claims edit method,a wrong resource was used previously
claims.dart modified
=> modified claims edit method

lib/services/keys.dart, lib/services/partners.dart
- Modified keys. added partner attributes  class, 
- Added modified partner identity create, edit identity
- Added partner get bank account, add bank account.
=> modified keys.

lib/services/keys.dart
- Added claims keys, 
1.  paymentMethodDescription,
2.  membership,
3.  statusDesccription
=> add-claim-approvals-view-keys

lib/mawa_package.dart, lib/services/keys.dart, lib/services/notifications.dart
- Created notifications methods, create, get specific, and get all notifications.
- Added the notification keys.
- Created the notifications class.
=> Add notification methods

lib/services/keys.dart, lib/services/partners.dart
-Modified the partner edit method
-Modified the add address method(added partner id to the body)
-Create the new bank details edit method
-Create the new delete bank account method(i.e delete bank).
-Modified addBankDetails method(added branch name to the body, and change type to account type on the body).
-Modified addAddress method (added the partnerId to the body).
-Modified the keys file,added new partner keys.
=> Update partner methods

lib/services/keys.dart, lib/services/partners.dart
-Modified the add address method(added partner id to the body) -Create the new bank details edit method
-Create the new delete bank account method(i.e delete bank). -Modified addBankDetails method(added branch name to the body, and change type to account type on the body). -Modified addAddress method (added the partnerId to the body). -Modified the keys file,added new partner keys.
=> -Modified the partner edit method

lib/services/keys.dart, lib/services/partners.dart
-Updated the edit address method header, added partner id to the header
-Updated the edit address method body, Added the address id to the body
-Updated the identity edit method, added the partner id to the body
-Updated the delete address, added the address id to the header.\
-Added the address keys.
=> Update partner address methods

lib/services/partners.dart
- Removed the require word from the add bank details method arguments.
=> Deployment is failing on dev #471

lib/services/keys.dart
added 2 new  keys to accommodate changes in group society response
=> keys update for group society panels

lib/screens/attach_base64_file.dart, lib/services/attachment.dart, lib/services/keys.dart
#476
- updated get for transaction
- updated delete
- removed unnecessary methods
- updated post
=> Update attachment methods

lib/services/keys.dart, lib/services/payment_requests.dart
- added approve payment method
- added cancel payment method
- added reject payment method
- added complete payment method
- added submit payment method
- updated payment req. keys (added complete resource key).
=> Add more payment request methods. #479

lib/services/bank.dart, lib/services/keys.dart
-added bank.dart
-added Bank Service to accomodate the bank0account resource
-added the post mehod
-added the get method for all bank account details of a specific objectId/transactionNo
-added the bank-account in the keys.dart reources class
=> new services for transaction bank details #488

lib/services/keys.dart
-added payment request remapping keys:
> recipient
>employeeResponsible
=> Add payment request keys #491

lib/services/keys.dart
Change cancel resource key from Cancel to cancel.
=> Rectify cancel key in the resource class. #494

example/test/widget_test.dart, lib/services/receipts.dart
- Upadated create, get, getAll, and search methods to match recent bes changes
- removed unnecessary methods
=> Receipt match changes on mawa bes #497

example/test/widget_test.dart, lib/services/receipts.dart
=> Receipt: Match changes on mawa-bes

lib/services/keys.dart
- added payment request status reason key.
=> Add Payment Request Status Reason Field #504

lib/screens/alerts.dart
=> New alert method

lib/services/service_request.dart
updated service request methods
=> Service request updating

lib/keys/field_option_types.dart, lib/keys/json_responses.dart, lib/services/products.dart
updated product create to match bes changes
added new keys
=> Product api call changes

lib/keys/field_option_types.dart, lib/keys/json_responses.dart, lib/services/address.dart, lib/services/products.dart
- added the city, suburb Json response keys
- Modified the create and edit body, added the city json payload to the body.
=> Modified address method #518

lib/keys/json_responses.dart, lib/keys/resources.dart, lib/services/group_society.dart
=> Group representatives add group representatives related methods

lib/keys/json_responses.dart, lib/keys/resources.dart, lib/services/group_society.dart
#521 
- added create, get, and delete methods for representatives.
=> Group representatives: add group representatives related methods

lib/keys/json_responses.dart
=> New response key

lib/services/attachment.dart
removed decode on attachment GET specific method
=> Attachment download

lib/keys/json_payloads.dart, lib/keys/json_responses.dart, lib/services/employment.dart
modified the employment create method,
modified the edit employment method
modified terminate, suspend and rehire methods
added the Json response and Json payload response
=> Modify employment methods #528

lib/keys/field_option_types.dart, lib/keys/json_payloads.dart, lib/services/group_society.dart
- added balances add
- added json payloads key
- added field key
=> Group Society Status & Once-off Edit on Balances

lib/keys/json_responses.dart, lib/keys/resources.dart, lib/services/products.dart
- added new keys
- added product category related methods
=> product category

lib/services/group_society.dart
made the group society creation type nullable
=> group society creation type

lib/keys/json_payloads.dart, lib/keys/json_responses.dart, lib/services/claim.dart
- added informantId field on claim create method 
- added informantId key json payloads
- added informant key on json responses
=> informant add

lib/keys/json_payloads.dart, lib/keys/resources.dart, lib/mawa_package.dart, lib/services/pricing_engine.dart
- Added the class pricing_engine
- Added the method calculate pricing
- Add the pricing engine resource
- Added the pricing Json payload fields
=> Add pricing engine class #552

lib/keys/json_payloads.dart, lib/services/invoice.dart
- Modified the invoice create methods, added sales representative, pricing fields, modify items data type.
- Added more invoice Json payload, added invoice date, payment terms.
=> Modify invoice create method. #555

lib/keys/resources.dart, lib/services/cases.dart
-added cases.dart
-added the get all mehod
-added the get method get specific
-added case_ resource keys
resources.dart modified
cases.dart created
=> Case Create Page Requirement #1183

lib/keys/json_responses.dart
=> -added json responses

lib/keys/json_payloads.dart, lib/services/cases.dart
-added json payloads
-added the create method
cases.dart modified
json_payloads.dart modified
=> Law case methods

lib/services/cashup.dart
=> Modify the create cash up #563

lib/keys/json_responses.dart
=> new voucher key

lib/keys/json_payloads.dart, lib/keys/json_responses.dart, lib/services/invoice.dart, lib/services/items.dart
-Modified items edit
-Modified items add method
-Added invoice delete method
-Modified Json Payload class
-Modified Json Response class.
=> Modify_items_add_edit_methods

lib/services/products.dart
corrected variable name for price on create
=> Variable wording correcting

lib/mawa.dart, lib/services/network_requests.dart
allowed the acceptance and saving of tenant ID in initialization
=> allowing the saving of tenant ID to shared preferences

lib/keys/query_parameters.dart, lib/services/cashup.dart, lib/services/user.dart
-Added the cash up type parameter.
_Added keys fields.
=> Modified the cashup #576

lib/keys/resources.dart, lib/services/claim.dart, lib/services/user.dart
=> Match User class to Backend

lib/keys/json_payloads.dart, lib/services/cashup.dart
added the manual cashup create method
=> Add the manual create cash up method #581

lib/keys/field_option_types.dart, lib/keys/json_responses.dart, lib/services/cases.dart
-added court and caseType under jsonResponses
-added option types
-added product on the create parameters
cases.dart modified
field_option_types.dart modified
json_responses.dart modified
=> case modification

lib/keys/resources.dart, lib/services/claim.dart, lib/services/user.dart
=> Merge User class to Backend

lib/keys/json_responses.dart, lib/services/cashup.dart
- Added the from and to receipt on the payload.
- Added the cash up type on the payload.
- Removed the amount on the payload.
=> Modified receipt cash up create

lib/services/authenticate.dart, lib/services/network_requests.dart
=> User login user should be notified why they can't login 

lib/services/claim.dart
=> Claim reject not working

lib/keys/id_types.dart, lib/mawa_package.dart
https://github.com/mawa-za/mawa/issues/1482
=> Live] testing (memebrship ) partner create sa id not validating 

lib/keys/id_types.dart, lib/mawa_package.dart
https://github.com/mawa-za/mawa/issues/1482
=> [Live] Testing (Memebrship ) Partner create: SA ID not Validating

lib/services/cases.dart
=> -added delete method

pubspec.yaml
upgraded some packages in pubspec.yaml
=> Packages upgrade

pubspec.yaml
downgraded permision_handler to version 10.4.5
=> GitHub build fail fix

lib/services/products.dart
=> Alpha] testing (system configuration) product doesn't edit successfully

lib/keys/membership_creation_types.dart, lib/mawa_package.dart
added class MembershipCreationTypes
=> Development (Memberships) Membership History Panel

lib/keys/json_payloads.dart, lib/services/invoice.dart
adding transactionID and invoiceType in Invoice payload
=> Adding fields in invoice payload

lib/keys/json_payloads.dart, lib/services/invoice.dart
adding transactionID and invoiceType in Invoice payload
=> adding transactionID and invoiceType in Invoice payload

lib/keys/field_option_types.dart
Added new document type fields
=> Add new attachment document type fields

lib/keys/field_option_types.dart
-added this fields, document type deposit, document type cash up, document type payment request
=> add new document type fields

lib/keys/resources.dart, lib/services/deposit.dart
- Added the new deposit attachment create method.
- Added deposit attachment resource
=> Add the deposit attachment

lib/keys/field_option_types.dart, lib/screens/attach_base64_file.dart
allowed receing of documenttype field from constractor to make attachment type dynamic
=> Allow attachment document type to be dynamic

lib/keys/json_responses.dart
Added the Json Response key attachment
=> add attachment jsonResponse

lib/keys/json_payloads.dart, lib/keys/json_responses.dart, lib/keys/query_parameters.dart, lib/keys/resources.dart, lib/keys/shared_preferences.dart, lib/services/network_requests.dart, lib/services/service_request.dart
- updated edit method
- added new methods
- added new keys
=> service request and keys update

lib/keys/json_payloads.dart, lib/keys/json_responses.dart, lib/keys/query_parameters.dart, lib/mawa_package.dart, lib/screens/alerts.dart, lib/services/comment.dart
updating Add-new-functionality-for-Comments from master
=> Add new functionality for Comments

lib/services/products.dart
=> [Alpha] Testing (System Configuration) Product Doesn't Edit Successfully

lib/services/field.dart
added method to get all field options
=> Development get all field options on login

lib/services/field.dart
added method to get all field options
=> Development - get all field options on login

lib/services/booking.dart
adding a bookStatus parameter to enable changing a status from the appointment
=> new package

lib/keys/json_responses.dart
- Added the invoice type Json response key
=> Add invoice type json response key

lib/keys/json_responses.dart
- Added the invoice type Json response key
=> add-invoice-type-json-response-key

lib/keys/field_option_types.dart, lib/keys/resources.dart, lib/services/membership.dart
Made accommodations for membership approving
=> Membership Approval

lib/keys/json_responses.dart, lib/keys/resources.dart, lib/services/partners.dart
-added new search method
-added partner/v2 resource
-added JsonResponses
resources.dart modified
json_responses.dart modified
partners.dart modified
=> [Beta] Testing (Customer) Records are not loading #1494-packageChanges

lib/keys/json_responses.dart, lib/keys/query_parameters.dart, lib/keys/resources.dart, lib/services/membership.dart
#641 
added new search method for search endpoint v2
added new keys
=> Membership   implement search v2 endpoint

lib/services/membership.dart
added body to endpoint call for methods cancel, activate, and deactivate
=> correcting membership action methods

lib/keys/json_responses.dart, lib/keys/query_parameters.dart, lib/keys/resources.dart, lib/services/membership.dart
=> Remove duplicate key

lib/keys/json_payloads.dart, lib/services/cases.dart
Adding services providers parameter
=> Adding services providers parameter

lib/keys/json_payloads.dart, lib/services/cases.dart
adding serviceProviders as a parameter
=> adding serviceProviders as a parameter

lib/services/cases.dart
Reverting parameter changes back to the previous ones.
=> Reverting parameter changes

lib/services/cases.dart
Reverting parameter changes back to the previous ones.
=> Reverting parameter changes back to the previous ones.

lib/mawa_package.dart, lib/services/field.dart
https://github.com/mawa-za/mawa/issues/1678
- made validity date to not be mandatory
- added default values if validity dates were not supplied
=> Field option create altering

lib/keys/partner_types.dart, lib/services/strings.dart
MSBS-60
- modified partner type individual
- added person name deciphering for v2 of the partner search
=> MSBS-60-Membership-creation-failing

lib/keys/json_payloads.dart, lib/services/premium.dart
MSBS-58
- added payload key
- modified premium create to accommodate employee responsible
=> MSBS-58-Premium-processing-failing

lib/keys/json_responses.dart, lib/keys/resources.dart, lib/services/claim.dart
-added JsonResponses
-added resoures
resources.dart modified
json_responses.dart modified
claim.dart modified
=> added the v2 endpoint

lib/services/cashup.dart
- created V2 of the search method
- reformatted the code
=> Msbs 90 investigate and provide solution

lib/services/cashup.dart
- created V2 of the search method
- reformatted the code
=> MSBS-90-Investigate-and-provide-solution

lib/keys/json_payloads.dart, lib/keys/json_responses.dart, lib/services/claim.dart
Msbs 192
-Added the paidOutAmount on the claim edit
- Added paidOutAmount claim field the json payload/ responses key
=> Msbs 192 development cash claim amount to be editable on claim approval

lib/services/cases.dart
-modified the create method to match the new backend POST
cases.dart modified
=> MSBS-176-Investigate: Case Create Screen: Create Button not working

lib/keys/json_responses.dart
=> MSBS-282 new response key add

lib/keys/json_responses.dart, lib/services/service_request.dart
modified the service request create method to match the BES
=> Msbs 55 no customer linked to the task and service request

lib/services/group_society.dart
created method for v2 of the group society search endpoint
=> Msbs 347 investigate claim create taking long to load in the claim work centre and membership

lib/services/claim.dart
Create added the claim payment request
=> Msbs 379 development claim approval automatic payment request creation

lib/services/claim.dart
MSBS-379
- Added the claim payment request endpoint.
=> MSBS-379-development-claim-approval-automatic-payment-request-creation

lib/services/task.dart
-added startDate and taskDuration
-removed "required" on post fields
task.dart modified
=> MSBS-235-Development: Change the generate invoice button to +task and allow multiple tasks to be added

lib/services/tools.dart
modified logout popup to accept function to use after logging out
=> Msbs 314 development add a timeout pop up when a user has been logged in without any action on their screen

lib/services/payment_requests.dart
MSBS-847
- added the status parameter to filter payment request using status
=> Msbs 847 development payment request approval search visual enhancements

lib/keys/resources.dart, lib/services/membership.dart
Adding get endPoint service to get all invoices that are created for a specific membership.
Adding a post endPoint service to download the invoice in pdf format.
=> Msbs 714 development membership billing

lib/services/claim.dart
Adding an End point service to download claim form as a pdf file
=> Msbs 808 development claim form pdf printing functionality

lib/keys/json_payloads.dart, lib/keys/resources.dart, lib/mawa_package.dart, lib/screens/forgot_password.dart, lib/services/reset_password.dart
=> MSBS-833 Development Self-service Password reset

lib/keys/json_responses.dart
MSBS-1062
-Added the batch number Json response key on json_responses.dart
=> Msbs 1062 development populate the batch number on the payment request

lib/keys/json_responses.dart
=> Msbs 1127 membership upgrade bug

lib/keys/json_responses.dart
=> MSBS-127 new json response key

lib/keys/query_parameters.dart, lib/services/partners.dart
MSBS-785
-Added the partner v2 search method
-updated the query parameters
=> Msbs 785 development partner search before record display sibo

lib/services/partners.dart
updated mehtod getSpecifIdentity() for partner GET using id number and type
=> Msbs 935 investigate unable to add an id to a customer

lib/services/partners.dart
updated mehtod getSpecifIdentity() for partner GET using id number and type
=> MSBS-935 partner get using id type and number
